version: "3.8"

services:
  sshd:
    container_name: sshd
    build:
        context: ./
        dockerfile: sshd.Dockerfile
    image: dhnt/sshd
    restart: always
    ports:
      - "5022:22"

  ipfs:
    container_name: ipfs
    build:
        context: ./
        dockerfile: ipfs.Dockerfile
    image: dhnt/ipfs
    environment:
      - IPFS_PATH=/data/ipfs
      - IPDR_CID_STORE=/data/ipdr/cids
    #   - IPDR_CID_RESOLVER=file:/data/ipdr/cids
    restart: always
    ports:
      # ipdr port
      # - "5000:5000"
      # ipfs ports
      # Swarm TCP; should be exposed to the public
      - "4001:4001"
      # Swarm UDP; should be exposed to the public
      - "4001:4001/udp"
      # Daemon API; must not be exposed publicly but to client services under you control
      - "5001:5001"
      # Web Gateway; can be exposed publicly with a proxy, e.g. as https://ipfs.example.org
      - "8080:8080"
      # Swarm Websockets; must be exposed publicly when the node is listening using the websocket transport (/ipX/.../tcp/8081/ws).
      - "8081:8081"
    volumes:
      - $HOME/.dhnt/ipfs:/data
